/**
  ******************************************************************************
  * @file    system_cx32l003.c
  * @author  MCU Application Team
  * @version V0.0.0
  * @date    05-December-2018
  * @brief   CMSIS Cortex-M0 Device Peripheral Access Layer System Source File.
  *          This file contains the system clock configuration for Cx32l003 devices,
  *          and is generated by the clock configuration tool  
  *          Cx32l003_Clock_Configuration_V1.0.0.xls
  *
  * 1.  This file provides two functions and one global variable to be called from 
  *     user application:
  *      - SystemInit(): Setups the system clock (System clock source, 
                         Divider factors, AHB/APBx prescalers and Flash settings),
  *                      depending on the configuration made in the clock xls tool.
  *                      This function is called at startup just after reset and 
  *                      before branch to main program. This call is made inside
  *                      the "startup_cx32l003.s" file.
  *
  *      - SystemCoreClock variable: Contains the core clock (HCLK), it can be used
  *                                  by the user application to setup the SysTick 
  *                                  timer or configure other parameters.
  *
  *      - SystemCoreClockUpdate(): Updates the variable SystemCoreClock and must
  *                                 be called whenever the core clock is changed
  *                                 during program execution.
  *
  * 2. After each device reset the HSI (8 MHz Range) is used as system clock source.
  *    Then SystemInit() function is called, in "startup_cx32l003.s" file, to
  *    configure the system clock before to branch to main program.
  *
  * 3. If the system clock source selected by user fails to startup, the SystemInit()
  *    function will do nothing and HSI still used as system clock source. User can 
  *    add some code to deal with this issue inside the SetSysClock() function.
  *
  * 4. The default value of HSE crystal is set to 8MHz, refer to "HSE_VALUE" define
  *    in "cx32l003.h" file.  you are using different crystal you have to adapt the HSE
  *    value to your own configuration.
  *
  * 5. This file configures the system clock as follows:
  *=============================================================================
  *                         System Clock Configuration
  *=============================================================================

  *-----------------------------------------------------------------------------
  *        SYSCLK                       | 24000000 Hz
  *-----------------------------------------------------------------------------
  *        HCLK                         | 24000000 Hz
  *-----------------------------------------------------------------------------
  *        AHB Prescaler                | 1
  *-----------------------------------------------------------------------------
  *        APB Prescaler                | 1
  *-----------------------------------------------------------------------------
  *        VDD                          | 3.3 V
  *-----------------------------------------------------------------------------
   *=============================================================================
  *****************************************************************************
  * @attention
  * <h2><center>&copy; COPYRIGHT 2020 CX</center></h2>
  * Unless required by applicable law or agreed to in writing;
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  *****************************************************************************
  */

/** @addtogroup CMSIS
  * @{
  */

/** @addtogroup CX32l003_system
  * @{
  */  
  
/** @addtogroup CX32l003_System_Private_Includes
  * @{
  */

#include "cx32l003.h"

/**
  * @}
  */

/** @addtogroup CX32l003_System_Private_TypesDefinitions
  * @{
  */

/**
  * @}
  */

/** @addtogroup CX32l003_System_Private_Defines
  * @{
  */
/**
  * @}
  */

/** @addtogroup CX32l003_System_Private_Macros
  * @{
  */

/**
  * @}
  */

/** @addtogroup CX32l003_System_Private_Variables
  * @{
  */
uint32_t SystemCoreClock    = 4000000;
__I uint8_t AHBPrescTable[16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9};

/**
  * @}
  */

/** @addtogroup CX32l003_System_Private_FunctionPrototypes
  * @{
  */

static void SetSysClock(void);

/**
  * @}
  */

/** @addtogroup CX32l003_System_Private_Functions
  * @{
  */

/**
  * @brief  Setup the microcontroller system.
  * @param  None
  * @retval None
  */
void SystemInit (void)
{  
   
	/*set system clock*/
  SetSysClock();
}

/**
  * @brief  Update SystemCoreClock according to Clock Register Values
  *         The SystemCoreClock variable contains the core clock (HCLK), it can
  *         be used by the user application to setup the SysTick timer or configure
  *         other parameters.
  *
  * @note   Each time the core clock (HCLK) changes, this function must be called
  *         to update SystemCoreClock variable value. Otherwise, any configuration
  *         based on this variable will be incorrect.         
  *
  * @note   - The system frequency computed by this function is not the real 
  *           frequency in the chip. It is calculated based on the predefined 
  *           constant and the selected clock source:
  * @param  None
  * @retval None
  */
void SystemCoreClockUpdate (void)
{
    
}

/**
  * @brief  Configures the System clock frequency, AHB/APB prescalers and Flash
  *         settings.
  * @note   This function should be called only once the RCC clock configuration
  *         is reset to the default reset state (done in SystemInit() function).
  * @param  None
  * @retval None
  */
static void SetSysClock(void)
{
/* д╛хо4Mhz*/
    /*close lock*/
    RCC->UNLOCK = 0x55aa6699;
    /*Enable HIRC 4MHz clock source*/
    RCC->SYSCLKCR = 0x5a690001;
    /*Select system clock*/
    RCC->SYSCLKSEL = 0x5a690001;
    /*open lock*/
    RCC->UNLOCK = 0x55aa6698;
}



/**
  * @}
  */

/**
  * @}
  */

/**
  * @}
  */

/************************ (C) COPYRIGHT  CX32*****END OF FILE****/
